---
galaxy_info:
  author: Lenny Shirley
  description: Retrieve a refresh token for the Red Hat API using an offline token.
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies: []
...
