---
namespace: infra
name: support_assist
version: 1.0.0-devel
description: Ansible Collection that will gather various reports/outputs that are commonly asked for in Red Hat Support Cases
readme: README.md
authors:
  - Lenny Shirley
repository: https://github.com/redhat-cop/infra.support_assist
issues: https://github.com/redhat-cop/infra.support_assist/issues
documentation: https://github.com/redhat-cop/infra.support_assist/docs
build_ignore: []
license:
  - GPL-3.0-or-later
tags:
  - support
  - sosreport
  - mustgather
dependencies: {}
...
