---
namespace: infra
name: support_assist
version: 0.1.0-devel
description: Ansible Collection that will gather various reports/outputs that are commonly asked for in Red Hat Support Cases
readme: README.md
authors:
  - Lenny Shirley @lennysh
  - David Mateus @dfelipem
repository: https://github.com/redhat-cop/infra.support_assist.git
issues: https://github.com/redhat-cop/infra.support_assist.git/issues
documentation: https://github.com/redhat-cop/infra.support_assist.git/docs
build_ignore:
  - galaxy.yml.j2
  - release.yml
  - .github
  - "*.tar.gz"
  - tests/*
license:
  - GPL-3.0-or-later
tags:
  - tools
  - linux
  - infrastructure
  - support
  - sosreport
  - mustgather
dependencies:
  community.general: ">=11.4.0"
...
