---
namespace: infra
name: support_assist
version: 1.2.0
description: Ansible Collection that will gather various reports/outputs that are commonly asked for in Red Hat Support Cases
readme: README.md
authors:
  - Lenny Shirley @lennysh
  - Diego Mateus @dfelipem
repository: https://github.com/redhat-cop/infra.support_assist
issues: https://github.com/redhat-cop/infra.support_assist/issues
documentation: https://github.com/redhat-cop/infra.support_assist/blob/devel/README.md
build_ignore:
  - .ansible
  - .ansible-lint
  - .ansible-lint-ignore
  - .black.cfg
  - .code-workspace
  - .coverage
  - .cursor
  - .devcontainer
  - .flake8
  - .github
  - .hypothesis
  - .isort.cfg
  - .markdownlint.yml
  - .mlc_config.json
  - .mypy_cache
  - .pre-commit-config.yaml
  - .prettierignore
  - .pytest_cache
  - .rh_offline_token*
  - .ruff_cache
  - .vscode
  - .yamllint.yml
  - "*.code-workspace"
  - "*.egg-info"
  - "*.log"
  - "*.pyc"
  - "*.swp"
  - "*.tar.gz"
  - "*~"
  - changelogs/
  - collections/
  - devfile.yaml
  - galaxy.yml.j2
  - htmlcov*
  - ignore_*
  - inventory-*
  - playbooks/ignore_*
  - pyproject.toml
  - release.yml
  - requirements.txt
  - roles/ignore_*
  - roles/*/.gitattributes
  - roles/*/.gitignore
  - roles/*/.yamllint.yml
  - roles/*/molecule
  - test-requirements.txt
  - test-workflow.txt
  - tests/*
  - tox-ansible.ini
license:
  - GPL-3.0-or-later
tags:
  - ansible
  - automation
  - infrastructure
  - linux
  - mustgather
  - redhat
  - sosreport
  - support
  - tools
dependencies:
  ansible.controller: ">=4.6.0"
  ansible.platform: ">=2.5.0"
  community.general: ">=11.4.0"
...
