---
- name: Refresh Token | Get Red Hat SSO access token
  ansible.builtin.uri:
    url: "{{ rh_token_refresh_api_token_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ rh_token_refresh_api_offline_token }}"
    return_content: true
    status_code: 200
  register: token_response

- name: Refresh Token | Set access token fact
  ansible.builtin.set_fact:
    rh_token_refresh_api_access_token: "{{ token_response.json.access_token }}"

- name: Refresh Token | Cache the new token and timestamp locally
  ansible.builtin.copy:
    content: |
      {
        "token": "{{ rh_token_refresh_api_access_token }}",
        "timestamp": {{ lookup('pipe', 'date +%s') }}
      }
    dest: "{{ rh_token_refresh_token_cache_file }}"
    mode: '0600' # Set secure permissions for the token file.
...
