---
- name: Fetch | Set fact for the found directory path
  ansible.builtin.set_fact:
    _must_gather_source_path: "{{ ocp_must_gather_dest_dir }}"

- name: Fetch | Ensure necessary setup facts are gathered
  ansible.builtin.setup:
    filter:
      - ansible_fqdn
      - ansible_date_time

- name: Fetch | Set fact for the archive name
  ansible.builtin.set_fact:
    __must_gather_archive_name: >-
      {{ ('must-gather-' ~ cluster_name | lower ~ '-'
         ~ ansible_date_time.date
         ~ '-' ~ (ansible_date_time.time | replace(':',''))
         ~ '.tar.gz') | regex_replace('[^a-zA-Z0-9._-]', '-') }}

- name: Fetch | Create a compressed archive of the must-gather directory
  community.general.archive:
    path: "{{ _must_gather_source_path }}"
    dest: "{{ ocp_must_gather_dest_dir }}/{{ __must_gather_archive_name }}"
    format: gz
    mode: "0644"
  when: _must_gather_source_path is defined

- name: Fetch | Add must-gather archive path to case_updates_needed
  when:
    - ocp_must_gather_dest_dir is defined
    - ocp_must_gather_dest_dir | length > 0
    - __must_gather_archive_name is defined
    - __must_gather_archive_name | length > 0
  ansible.builtin.set_fact:
    case_updates_needed: >-
      {{ case_updates_needed | default([]) +
      [{
        'hostname': cluster_name,
        'attachment': ocp_must_gather_dest_dir ~ '/' ~ __must_gather_archive_name,
        'attachmentDescription': (
          "OpenShift must-gather collected from '" ~ cluster_name ~ "' cluster accessed via execution host " ~ inventory_hostname
          ~ " (" ~ (ansible_fqdn | default('N/A')) ~ ") using the 'infra.support_assist' collection."
        )
      }] }}
...
