---
- name: Login | Run oc login
  ansible.builtin.command: >
    oc login
    --token={{ ocp_must_gather_token }}
    --server={{ ocp_must_gather_server_url }}
  register: oc_login_result
  changed_when: oc_login_result.rc == 0
  ignore_errors: true

- name: Login | Verify 'oc' authentication
  ansible.builtin.command: oc whoami
  register: oc_whoami
  changed_when: false
  ignore_errors: true

- name: Login | Fail if not logged into OpenShift cluster
  ansible.builtin.fail:
    msg: |
      Failed to verify OpenShift authentication using 'oc whoami' on execution host ({{ inventory_hostname }}).
      Login Error (if any): {{ oc_login_result.stderr | default(oc_login_result.stdout | default('No output')) }}
      Whoami Error (if any): {{ oc_whoami.stderr | default(oc_whoami.stdout | default('No output')) }}
  when: oc_login_result.rc != 0 or oc_whoami.rc != 0
...
