---
- name: "Attachment Upload | Upload attachment to case {{ case_id ~ ' | ' ~ case_update.attachment | basename }}" # noqa: command-instead-of-module
  register: upload_cli_result
  no_log: true
  ignore_errors: true
  changed_when: upload_cli_result.rc == 0
  async: "{{ rh_case_update_timeout | int + 60 }}" # Allow up to rh_case_update_timeout + 1 minute for attachment upload
  poll: 10 # Check every 10 seconds
  ansible.builtin.shell: |
    curl -s -X POST \
      -w "\nHTTP_STATUS:%{http_code}" \
      --max-time {{ rh_case_update_timeout }} \
      -H "Authorization: Bearer {{ rh_token_refresh_api_access_token }}" \
      -F "file=@{{ case_update.attachment }};filename={{ case_update.attachment | basename }}" \
      -F "description={{ case_update.attachmentDescription | default('') }}" \
      "https://api.access.redhat.com/support/v1/cases/{{ case_id }}/attachments/"

- name: Attachment Upload | Parse curl output from loop
  ansible.builtin.set_fact:
    __curl_stdout: "{{ upload_cli_result.stdout | default('N/A') }}"
    __curl_stderr: "{{ upload_cli_result.stderr | default('N/A') }}"
    __curl_rc: "{{ upload_cli_result.rc | default('N/A') }}"

- name: Attachment Upload | Extract HTTP status and response body
  ansible.builtin.set_fact:
    upload_status: "{{ (__curl_stdout | regex_search('HTTP_STATUS:(\\d+)', '\\1') | first | default(0)) | int }}"
    upload_body_raw: "{{ __curl_stdout | regex_replace('\\nHTTP_STATUS:.*$', '') }}"

- name: Attachment Upload | Fail if curl command failed or status not 20x
  ansible.builtin.fail:
    msg: |
      Upload failed!
      Curl Command Return Code: {{ __curl_rc }}
      HTTP Status: {{ upload_status }}
      Stderr: {{ __curl_stderr }}
      Response Body: {{ upload_body_raw }}
  when: __curl_rc | int != 0 or upload_status | int not in [200, 201]

- name: Attachment Upload | Set final JSON response from successful upload
  ansible.builtin.set_fact:
    upload_result_json: "{{ upload_body_raw }}"
...
