---
- name: "Comment | Add comment to case {{ case_id }}"
  ansible.builtin.uri:
    url: "https://api.access.redhat.com/support/v1/cases/{{ case_id }}/comments"
    method: POST
    headers:
      Authorization: "Bearer {{ rh_token_refresh_api_access_token }}"
      Accept: "application/json"
      Content-Type: "application/json"
    body_format: json
    body:
      commentBody: "{{ case_update.comment }}"
      contentType: "{{ case_update.commentType | default('markdown') }}" # Options: 'markdown' or 'plaintext'
    status_code:
      - 200
    return_content: true
    validate_certs: true
  register: comment_api_result
  no_log: false

- name: Comment | Fail if comment creation failed
  ansible.builtin.fail:
    msg: |
      Failed to add comment to case {{ case_id }}!
      Status Code: {{ comment_api_result.status }}
      Response Body: {{ comment_api_result.content | default('N/A') }}
  when: comment_api_result.status != 200
...
