---
- name: Pre-Validation
  ansible.builtin.include_tasks: pre_val.yml

- name: Find all project YAML files
  ansible.builtin.find:
    paths: "{{ role_path }}/vars/projects.d"
    patterns:
      - "*.yml"
      - "*.yaml"
    file_type: file
  register: __project_files

- name: Process project files
  ansible.builtin.include_tasks: projects.yml
  loop: "{{ __project_files.files }}"
  loop_control:
    loop_var: __project_file
    label: "Processing project file: {{ __project_file.path | basename }}"

- name: Find all job template YAML files
  ansible.builtin.find:
    paths: "{{ role_path }}/vars/job_templates.d"
    patterns:
      - "*.yml"
      - "*.yaml"
    file_type: file
  register: __job_template_files

- name: Process job template files
  ansible.builtin.include_tasks: job_templates.yml
  loop: "{{ __job_template_files.files }}"
  loop_control:
    loop_var: __job_template_file
    label: "Processing job template file: {{ __job_template_file.path | basename }}"
...
