---
# Pre-validation tasks for aap_dispatch role

- name: Pre-Validation | Ensure hostname is provided
  ansible.builtin.assert:
    that:
      - aap_hostname is defined
      - aap_hostname | length > 0
    fail_msg: "AAP hostname is required. Please provide 'aap_hostname' as an extra-var or set the 'AAP_HOSTNAME', 'CONTROLLER_HOST', or 'TOWER_HOST' environment variable."

- name: Pre-Validation | Ensure either aap_username and aap_password are provided, or aap_token is provided
  ansible.builtin.assert:
    that:
      - (aap_token is defined and aap_token | length > 0) or
        ((aap_username is defined and aap_username | length > 0) and (aap_password is defined and aap_password | length > 0))
    fail_msg: "Either 'aap_token' must be provided, or both 'aap_username' and 'aap_password' must be provided. Please provide these as extra-vars or set the corresponding environment variables."


- name: Pre-Validation | Ensure organization is provided
  ansible.builtin.assert:
    that:
      - aap_dispatch_organization is defined
      - aap_dispatch_organization | length > 0
    fail_msg: "AAP organization is required. Please provide 'aap_dispatch_organization' as an extra-var."
...
