---
- name: Fetch | Find the generated SOS Report
  ansible.builtin.find:
    paths: /var/tmp
    patterns: sosreport-*.tar.xz
    age: -5m # Find reports created in the last 5 minutes to be safe
  register: found_sos_report

- name: Fetch | Case folder block
  vars:
    __dest_path: "{{ sos_report_dest }}/case_{{ case_id }}/{{ inventory_hostname | lower | regex_replace('[^a-zA-Z0-9_-]', '-') }}"
  block:
    - name: Fetch | Ensure destination folder exists
      ansible.builtin.file:
        name: "{{ __dest_path }}"
        state: directory
        mode: "0755"

    - name: Fetch | Fetch the SOS Report to the control node
      when: found_sos_report.matched > 0
      loop: "{{ found_sos_report.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      become: true
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ __dest_path }}/"
        flat: true

    - name: Fetch | Build case_updates_needed variable
      when: found_sos_report.matched > 0
      loop: "{{ found_sos_report.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      ansible.builtin.set_fact:
        case_updates_needed: >-
          {{ case_updates_needed | default([]) +
          [{
            'hostname': inventory_hostname,
            'fqdn': ansible_fqdn,
            'attachment': __dest_path ~ '/' ~ item.path | basename
          }] }}
...
