---
# This role is based on and adapted from code in the infra.aap_configuration collection
# https://github.com/redhat-cop/infra.aap_configuration
galaxy_info:
  author: Lenny Shirley
  description: Dispatches and manages AAP resources (job templates, projects, etc.)
  company: Red Hat
  issue_tracker_url: https://github.com/redhat-cop/infra.support_assist/issues
  license: GPL-3.0-or-later
  min_ansible_version: 2.16.0
  galaxy_tags:
    - aap
    - templates
    - projects
    - automation
    - infrastructure
    - linux
    - redhat
    - support
    - tools
dependencies: []
...
