---
# https://github.com/marketplace/actions/issues-helper
name: Issue Remove Labels

on:
  issues:
    types: [reopened]
  issue_comment:
    types: [created]

jobs:
  remove-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: remove inactive
        if: github.event.issue.state == 'open'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'inactive'
...
