---
# defaults file for aap_dispatch
aap_dispatch_secure_logging: "{{ var_no_log | default(aap_configuration_secure_logging) | default('false') }}"
aap_dispatch_async_retries: "{{ aap_configuration_async_retries | default(50) }}"
aap_dispatch_async_delay: "{{ aap_configuration_async_delay | default(1) }}"
aap_dispatch_loop_delay: "{{ aap_configuration_loop_delay | default(0) }}"
aap_dispatch_async_dir:
aap_dispatch_enforce_defaults: "{{ aap_configuration_enforce_defaults | default(false) }}"

aap_dispatch_organization: ""
...
